<?php
/**
 * @copyright Copyright © 2020 magesolution. All rights reserved.
 * @author    @copyright Copyright (c) 2014 magesolution (<https://www.magesolution.com>)
 * @license <https://www.magesolution.com/license-agreement.html>
 * @Author: ndthien0912<ndthien0912@gmail.com>
 * @github: <https://github.com/magesolution>
 */
?>
<?php
/**
 * @var $block \MGS\OSCheckout\Block\LayoutOnestepCheckout\Container
 */
?>
<h2 class="checkout-title"><?php echo $block->getCheckoutTitle(); ?></h2>
<p class="checkout-description">
    <?php echo $block->getCheckoutDescription(); ?>
</p>
