<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>

<?php
$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
$backgroundType = $themeSettingConfig->getStoreConfig('themesettings/page_title/background');
$layoutType = $themeSettingConfig->getStoreConfig('themesettings/page_title/design') ? $themeSettingConfig->getStoreConfig('themesettings/page_title/design') : 1;

$customClass = $customStyle = "";
if($backgroundType == 2){
	/* Image */
	if($image = $themeSettingConfig->getStoreConfig('themesettings/page_title/background_image')){
		$customClass = "ttbg-image";
		if($themeSettingConfig->getStoreConfig('themesettings/page_title/bg_repeat')){
			$customClass .= " ttbg-image-repeat";
		}
		$imageBg = $themeSettingConfig->getPageTitleBackground();
		$customStyle = "background-image: url(".$imageBg.");";
	}
}elseif($backgroundType == 3) {
	/* Color */
	if($color = $themeSettingConfig->getStoreConfig('themesettings/page_title/background_color')){
		$customClass = "ttbg-color";
		$customStyle = "background-color: ".$color.";";
	}
}
?>
<?php if ($title): ?>

    <div id="page-title-wrapper" class="layout_type<?= $layoutType ?> page-title-wrapper<?php /* @escapeNotVerified */ echo $cssClass; ?> <?= $customClass ?>" style="<?= $customStyle ?>">
        <h1 class="page-title"
            <?php if ($block->getId()): ?> id="<?php /* @escapeNotVerified */ echo $block->getId();?>" <?php endif; ?>
            <?php if ($block->getAddBaseAttributeAria()): ?>
                aria-labelledby="<?php /* @escapeNotVerified */ echo $block->getAddBaseAttributeAria(); ?>"
            <?php endif; ?>>
            <?php /* @escapeNotVerified */ echo $title ?>
        </h1>
        <?= $block->getChildHtml(); ?>
    </div>
    <?php if ($layoutType == 1) : ?>
        <script type="text/javascript">
            require(
                [
                    'jquery'
                ],function($){
                    $(document).ready(function(){
                        $(".breadcrumbs").appendTo("#page-title-wrapper");
                    });
                });
        </script>
    <?php endif; ?>
<?php endif; ?>

