<?php
/**
 * @copyright Copyright © 2020 magesolution. All rights reserved.
 * @author    @copyright Copyright (c) 2014 magesolution (<https://www.magesolution.com>)
 * @license <https://www.magesolution.com/license-agreement.html>
 * @Author: ndthien0912<ndthien0912@gmail.com>
 * @github: <https://github.com/magesolution>
 */
?>
<?php
/**
 * @var $block \MGS\OSCheckout\Block\Adminhtml\Order\View\Comment
 */
?>
<?php if ($block->getOrderDateTime()): ?>
    <section class="admin__page-section onestepcheckout-delivery-date">
        <div class="admin__page-section-item-title">
            <span class="title"><?= __('Delivery Date') ?></span>
        </div>
        <div class="admin__page-section-item-content">
            <span class="comment"><?php echo $block->getOrderDateTime() ?></span>
        </div>
    </section>
<?php endif ?>
<?php if ($block->getOrderComment()): ?>
    <section class="admin__page-section onestepcheckout-comment">
        <div class="admin__page-section-item-title">
            <span class="title"><?= __('Delivery Comment') ?></span>
        </div>
        <div class="admin__page-section-item-content">
            <span class="comment"><?php echo $block->getOrderComment() ?></span>
        </div>
    </section>
<?php endif ?>
