<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
$themeHelper = $this->helper('MGS\ThemeSettings\Helper\Config');

$lazyLoad = $themeHelper->getStoreConfig('themesettings/general/lazy_load');
$baseImage = $this->getViewFileUrl('MGS_ThemeSettings::images/blank.png');
$baseImageHover = $this->getViewFileUrl('MGS_ThemeSettings::images/blank.png');
$changeProductPerRow = $themeHelper->getEnableChangeProductPerRow();
$settings = $themeHelper->getThemeSettings();
$perrow = $settings['catalog']['per_row'];
$colCheck = $themeHelper->convertPerRowtoCol($perrow);
$colClass = $themeHelper->convertColClass($colCheck, 'col', null);

/* Theme config */
$_hideReview = $themeHelper->getStoreConfig('themesettings/catalog/review');
$_hideAddCart = $themeHelper->getStoreConfig('themesettings/catalog/add_to_cart');
$_hideWishlist = $themeHelper->getStoreConfig('themesettings/catalog/wishlist_button');
$_hideCompare = $themeHelper->getStoreConfig('themesettings/catalog/compare_button');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <div class="category-product-actions">
        <?php if ($block->getMode() == 'grid'): ?>
            <?php if ($changeProductPerRow): ?>
                <div class="change-product-per-row change-product-per-row-desktop button-group layout-mode-button-group">
                    <?php
                    $defaultValueProduct = $themeHelper->getDefaultValueNumberProductPerRow();
                    if ($defaultValueProduct == null) {
                        $defaultValueProduct = '4';
                    }
                    ?>
                    <?php $arrayValues = $themeHelper->getValuesNumberProductPerRow(); ?>
                    <?php foreach ($arrayValues as $number): ?>
                        <?php
                        switch ($number) {
                            case '1':
                                $classNumber = 'one';
                                $dataCol = '12';
                                break;
                            case '2':
                                $classNumber = 'two';
                                $dataCol = '6';
                                break;
                            case '3':
                                $classNumber = 'three';
                                $dataCol = '4';
                                break;
                            case '4':
                                $classNumber = 'four';
                                $dataCol = '3';
                                break;
                            case '5':
                                $classNumber = 'five';
                                $dataCol = '5';
                                break;
                            case '6':
                                $classNumber = 'six';
                                $dataCol = '2';
                                break;
                            case '7':
                                $classNumber = 'seven';
                                $dataCol = '7';
                                break;
                            case '8':
                                $classNumber = 'eight';
                                $dataCol = '8';
                                break;

                            default:
                                $classNumber = 'four';
                                $dataCol = '3';
                                break;
                        }
                        ?>
                        <a href="#" class="pr <?php echo $classNumber; if ($number == $defaultValueProduct) echo " active is-checked"; ?>" data-col="<?php echo $dataCol; ?>"></a>
                    <?php endforeach; ?>
                </div>
                <?php
                $colCheck = $themeHelper->convertPerRowtoCol($defaultValueProduct);
                $colClass = $themeHelper->convertColClass($colCheck, 'col', null);
                ?>
            <?php endif ?>
        <?php endif ?>
        <div class="filter-toggle">
            <a href="javascript:void(0)" class="title">
                <span class="icon pe-7s-edit"></span>
            </a>
        </div>
        <?= $block->getAdditionalHtml() ?>
        <?= $block->getToolbarHtml() ?>
    </div>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $image_hover = 'product_thumbnail_image';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $image_hover = 'product_thumbnail_image';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper mgs-products <?= /* @noEscape */
    $viewMode ?> products-<?= /* @noEscape */
    $viewMode ?>">
        <ol class="products list items product-items <?php if ($changeProductPerRow && $viewMode == 'grid'): ?>product-list-masonry-change-product line<?php endif ?>">
            <?php $_imageHelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
            <?php $size = $themeHelper->getImageSize(); ?>
            <?php $padding = $themeHelper->getImagePadding(); ?>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php if ($block->getMode() == 'grid'): ?>
                <?php $i = 0; ?>
                <?php foreach ($_productCollection as $_product): $i++;?>
                    <li class="item product <?php if ($changeProductPerRow): ?>product-item-masonry<?php else: ?><?php echo $themeHelper->getClearClass($perrow, $i) ?><?php endif ?> product-item-info product-item <?php echo $colClass ?>">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <?php $productImage = $_imageHelper->init($_product, $imageDisplayArea)->resize($size['width'], $size['height'])->getUrl(); ?>
                        <?php $productImageHover = $_imageHelper->init($_product, $image_hover)->resize($size['width'], $size['height'])->getUrl(); ?>
                        <?php if (!$lazyLoad): ?>
                            <?php $baseImage = $productImage ?>
                            <?php $baseImageHover = $productImageHover ?>
                        <?php endif ?>
                        <div class="product-top">
                            <a href="<?php echo $_product->getProductUrl() ?>"
                               style="padding-bottom: <?php echo $padding; ?>;"
                               class="product photo product-item-photo <?php if ((basename($_product->getData('thumbnail')) != 'no_selection') && (basename($_product->getData('thumbnail')) != basename($_product->getData('small_image')))): ?> has-hover-image<?php endif ?>"
                               tabindex="-1">
                                <img src="<?php echo $baseImage ?>" alt="<?php echo $_productNameStripped ?>"
                                     class="img-responsive product-image-photo img-thumbnail<?php if ($lazyLoad): ?> lazy<?php endif ?>"
                                     data-src="<?php echo $productImage ?>"/>

                                <?php if (basename($_product->getData('thumbnail')) != 'no_selection'): ?>
                                    <?php if (basename($_product->getData('thumbnail')) != basename($_product->getData('small_image'))): ?>
                                        <img src="<?php echo $baseImageHover ?>" alt="<?php echo $_productNameStripped ?>"
                                             class="img-responsive img-hover-show<?php if ($lazyLoad): ?> lazy<?php endif ?>"
                                             data-src="<?php echo $productImageHover ?>"/>
                                    <?php endif ?>
                                <?php endif ?>

                                <div class="product-image-photo"></div>
                            </a>
                            <!-- Product label-->
                            <?php echo $themeHelper->getProductLabel($_product); ?>
							<?php if(!$_hideWishlist || !$_hideCompare): ?>
								<ul data-role="add-to-links" class="actions-link actions-secondary">
									<?php if ($addToBlock = $block->getChildBlock('addto')): ?>
										<?= $addToBlock->setProduct($_product)->getChildHtml() ?>
									<?php endif; ?>
								</ul>
							<?php endif ?>
							
                            <div class="action-mobile">
                                <?php if ($_product->isSaleable() && !$_hideAddCart): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form"
                                          data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                          action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                          method="post">
                                        <input type="hidden"
                                               name="product"
                                               value="<?= /* @noEscape */
                                               $postParams['data']['product'] ?>">
                                        <input type="hidden"
                                               name="<?= /* @noEscape */
                                               Action::PARAM_NAME_URL_ENCODED ?>"
                                               value="<?=
                                               /* @noEscape */
                                               $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                               ?>">
                                        <?= $block->getBlockHtml('formkey') ?>
                                        <button type="submit"
                                                title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                class="action tocart btn-cart primary ">
                                            <span class="icon pe-7s-shopbag"></span>
                                            <span class="text"><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                        </button>
                                    </form>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <h5 class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                    <?= /* @noEscape */
                                    $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </h5>
							
							<?php if(!$_hideReview): ?>
								<?= $block->getReviewsSummaryHtml($_product, $templateType,true) ?>
							<?php endif ?>
							
                            <?= /* @noEscape */
                            $block->getProductPrice($_product) ?>
                            <?php if ($_product->isAvailable()): ?>
                                <?= $block->getProductDetailsHtml($_product) ?>
                            <?php endif; ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            <?php else: ?>
                <?php foreach ($_productCollection as $_product):?>
                    <li class="item product product-item-info product-item">
                        <div class="line">
                            <div class="col-des-3 col-tb-4 col-mb-12">
                                <div class="product-image-content">
                                    <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                    <?php $productImage = $_imageHelper->init($_product, $imageDisplayArea)->resize($size['width'], $size['height'])->getUrl(); ?>
                                    <?php $productImageHover = $_imageHelper->init($_product, $image_hover)->resize($size['width'], $size['height'])->getUrl(); ?>
                                    <?php if (!$lazyLoad): ?>
                                        <?php $baseImage = $productImage ?>
                                        <?php $baseImageHover = $productImageHover ?>
                                    <?php endif ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>"
                                       style="padding-bottom: <?php echo $padding; ?>;"
                                       class="product photo product-item-photo <?php if ((basename($_product->getData('thumbnail')) != 'no_selection') && (basename($_product->getData('thumbnail')) != basename($_product->getData('small_image')))): ?> has-hover-image<?php endif ?>"
                                       tabindex="-1">
                                        <img src="<?php echo $baseImage ?>" alt="<?php echo $_productNameStripped ?>"
                                             class="img-responsive product-image-photo img-thumbnail<?php if ($lazyLoad): ?> lazy<?php endif ?>"
                                             data-src="<?php echo $productImage ?>"/>

                                        <?php if (basename($_product->getData('thumbnail')) != 'no_selection'): ?>
                                            <?php if (basename($_product->getData('thumbnail')) != basename($_product->getData('small_image'))): ?>
                                                <img src="<?php echo $baseImageHover ?>" alt="<?php echo $_productNameStripped ?>"
                                                     class="img-responsive img-hover-show<?php if ($lazyLoad): ?> lazy<?php endif ?>"
                                                     data-src="<?php echo $productImageHover ?>"/>
                                            <?php endif ?>
                                        <?php endif ?>

                                        <div class="product-image-photo"></div>
                                    </a>

                                    <!-- Quick view-->
                                    <ul class="mgs-quickview actions-secondary"></ul>
                                    <!-- Product label-->
                                    <?php echo $themeHelper->getProductLabel($_product); ?>
                                </div>
                            </div>
                            <div class="col-des-9 col-tb-8 col-mb-12">
                                <div class="product details product-item-details">
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <h5 class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                            <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                                        </a>
                                    </h5>
									<?php if(!$_hideReview): ?>
										<?= $block->getReviewsSummaryHtml($_product, $templateType,true) ?>
									<?php endif ?>
                                    <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                    <?php if ($showDescription):?>
                                        <div class="product description product-item-description">
                                            <?= /* @noEscape */ $_helper->productAttribute(
                                                $_product,
                                                $_product->getShortDescription(),
                                                'short_description'
                                            ) ?>
                                        </div>
                                    <?php endif; ?>
                                    <ul class="actions-link">
                                        <li>
                                            <?php if ($_product->isSaleable() && !$_hideAddCart):?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form"
                                                      data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                                      action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                      method="post">
                                                    <input type="hidden"
                                                           name="product"
                                                           value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                    <input type="hidden"
                                                           name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                           value="<?=
                                                           /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                           ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            class="action tocart primary btn-cart">
                                                        <span class="icon pe-7s-shopbag"></span>
                                                        <span class="text"><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                            <?php endif; ?>
                                        </li>
										<?php if(!$_hideWishlist || !$_hideCompare): ?>
											<?php if ($addToBlock = $block->getChildBlock('addto')):?>
												<?= $addToBlock->setProduct($_product)->getChildHtml() ?>
											<?php endif; ?>
										<?php endif ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            <?php endif;?>
        </ol>
    </div>
    <div class="bottom-pagination">
        <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    </div>

    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
                }
            }
        }

        </script>
    <?php endif; ?>
<?php endif; ?>
<script>
    require([
        'jquery',
        'waypoints'
    ], function(jQuery){
        (function($) {
            $('.filter-toggle .title').click(function(){
                $('html').toggleClass('filter-open');
            });
        })(jQuery);
    });
</script>
<script type="text/javascript">

    requirejs([

        'require',

        'jquery',

        'mgsmasonry',

        'mgsvisible'

    ], function( require, $, Masonry) {

        require( [ 'bridget' ], function( jQueryBridget ) {

            jQueryBridget( 'masonry', Masonry, $ );

            $(window).load(function() {

                var $container = $('.product-list-masonry-change-product').masonry({
                    itemSelector: '.product-item-masonry',
                    columnWidth: '.product-item-masonry',
                    horizontalOrder: true,
                    initLayoutMasonry: false
                });

                $('.layout-mode-button-group').on( 'click', 'a', function() {

                    $container.masonry({
                        columnWidth: '.product-item-masonry',
                        maxHeight: 0,
                        initLayoutMasonry: false
                    });

                });

                // change is-checked class on buttons
                $('.button-group').each( function( i, buttonGroup ) {

                    var $buttonGroup = $( buttonGroup );

                    $buttonGroup.on( 'click', 'a', function() {
                        $buttonGroup.find('.is-checked').removeClass('is-checked');
                        $( this ).addClass('is-checked');
                    });

                });

            });

            $(document).ajaxComplete(function() {

                var $container = $('.product-list-masonry-change-product').masonry({
                    itemSelector: '.product-item-masonry',
                    columnWidth: '.product-item-masonry',
                    horizontalOrder: true,
                    initLayoutMasonry: true
                });


                $('.layout-mode-button-group').on( 'click', 'a', function() {
                    $container.masonry({
                        columnWidth: '.product-item-masonry',
                        maxHeight: 0,
                        initLayoutMasonry: false
                    });

                });

                // change is-checked class on buttons
                $('.button-group').each( function( i, buttonGroup ) {
                    var $buttonGroup = $( buttonGroup );
                    $buttonGroup.on( 'click', 'a', function() {
                        $buttonGroup.find('.is-checked').removeClass('is-checked');
                        $( this ).addClass('is-checked');
                    });

                });
                $(window).scroll(function(){
                    $(".product-list-masonry-change-product > .product-item-masonry").each(function(){
                        if($(this).visible(true,true,'vertical')) {
                            $(this).addClass('enable');
                        }else {
                            $(this).removeClass('enable');
                        }
                    });
                });

            });

        });

    });

</script>
<script>
    require(['jquery', 'domReady!'], function ($) {
        $(document).ready(function(){
            $(window).scroll(function(){
                $('.category-product-actions .change-product-per-row a.active').trigger('click');
            });
        });
    });
</script>
