<?php
/**
 * @copyright Copyright © 2020 magesolution. All rights reserved.
 * @author    @copyright Copyright (c) 2014 magesolution (<https://www.magesolution.com>)
 * @license <https://www.magesolution.com/license-agreement.html>
 * @Author: ndthien0912<ndthien0912@gmail.com>
 * @github: <https://github.com/magesolution>
 */
?>
<?php
/**
 * @var $block \MGS\OSCheckout\Block\LayoutOnestepCheckout\Order\View\Comment
 */
?>
<?php if ($orderDate = $block->getOrderDateTime()): ?>
    <div class="box box-order-date">
        <strong class="box-title">
            <span><?php echo __('Delivery Date') ?></span>
        </strong>
        <div class="box-content">
            <?php echo $orderDate; ?>
        </div>
    </div>
<?php endif; ?>
<?php if ($commentHtml = $block->getOrderComment()): ?>
    <div class="box box-order-comment">
        <strong class="box-title">
            <span><?php echo __('Delivery Comment') ?></span>
        </strong>
        <div class="box-content">
            <?php echo $commentHtml; ?>
        </div>
    </div>
<?php endif; ?>
