<?php
/*
* 	Block Guide
*	Report Bug: $block->getChildHtml('report.bugs');
*	Store Swicher: $block->getChildHtml('store_switcher');
*	Footer Links: $block->getChildHtml('footer_links');
*	Copyright: $block->getChildHtml('copyright');
*	Form Subcribe: $block->getChildHtml('form.subscribe');
*	Static block: $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('your_block_identifier')->toHtml();
*/
?>

<?php
	$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
	$footerVersion = $themeSettingConfig->getStoreConfig('themesettings/footer/footer_version');
	$footerParallax = $themeSettingConfig->getStoreConfig('themesettings/footer/parallax');
	$footerBottomCustomCopyright = $themeSettingConfig->getStoreConfig('themesettings/footer/footer_bottom_custom_copyright');
	$customFooterBottomCopyright = $themeSettingConfig->getStoreConfig('themesettings/footer/footer_bottom_copyright');
	if($footerVersion == ''){ $footerVersion = 'footer1'; }
?>
<div class="footer-container <?= $footerVersion; ?> <?php if($footerParallax): ?>footer-parallax<?php endif ?>">
	<?php if($footerVersion == 'footer1'): ?>
		<div class="middle-footer">
			<div class="frame">
				<div class="line">
                    <div class="col-des-3 col-tb-6 col-mb-12">
                        <!-- Static block: footer_contact_us -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer1_contact_us')->toHtml() ?>
                        <?= $block->getChildHtml('store_switcher'); ?>
                    </div>
                    <div class="col-des-2 col-tb-6 col-mb-12">
                        <!-- Static block: footer_block_categories -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_categories')->toHtml() ?>
                    </div>
                    <div class="col-des-2 col-tb-6 col-mb-12">
                        <!-- Static block: footer_block_infomation -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_infomation')->toHtml() ?>
                    </div>
                    <div class="col-des-2 col-tb-6 col-mb-12">
                        <!-- Static block: footer_block_quick_link -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_quick_link')->toHtml() ?>
                    </div>
                    <div class="col-des-3 col-tb-6 col-mb-12">
                        <!-- Static block: footer_block_subscribe -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_subscribe')->toHtml() ?>
                    </div>
				</div>
			</div>
		</div>
		<div class="bottom-footer">
			<div class="frame">
                <div class="line">
                    <div class="col-des-6 col-tb-12 col-mb-12 copyright">
                        <address>
                            <?php if($footerBottomCustomCopyright): ?>
                                <?= $customFooterBottomCopyright; ?>
                            <?php else: ?>
                                <?= /* @escapeNotVerified */ $block->getChildHtml('copyright') ?>
                            <?php endif; ?>
                        </address>
                    </div>
                    <div class="col-des-6 col-tb-12 col-mb-12">
                        <!-- Static block: footer_block_menu_bottom -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_menu_bottom')->toHtml() ?>
                    </div>
                </div>
            </div>
		</div>
	<?php elseif($footerVersion == 'footer2'): ?>
        <div class="top-footer">
            <div class="frame">
                <!-- Static block: footer_block_subscribe -->
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_newsletter_top')->toHtml(); ?>
            </div>
        </div>
		<div class="middle-footer">
			<div class="frame">
				<div class="line">
                    <div class="col-des-3 col-tb-6 col-mb-12">
                        <!-- Static block: footer_contact_us -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer1_contact_us')->toHtml(); ?>
                        <?= $block->getChildHtml('store_switcher'); ?>
                    </div>
                    <div class="col-des-2 col-tb-6 col-mb-12">
                        <!-- Static block: footer_block_categories -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_categories')->toHtml(); ?>
                    </div>
                    <div class="col-des-2 col-tb-6 col-mb-12">
                        <!-- Static block: footer_block_infomation -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_infomation')->toHtml(); ?>
                    </div>
                    <div class="col-des-2 col-tb-6 col-mb-12">
                        <!-- Static block: footer_block_quick_link -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_quick_link')->toHtml(); ?>
                    </div>
                    <div class="col-des-3 col-tb-6 col-mb-12">
                         <!-- Static block: footer_block_instagram -->
                         <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_instagram')->toHtml(); ?>
                    </div>
				</div>
			</div>
		</div>
		<div class="bottom-footer">
			<div class="frame">
                <div class="line">
                    <div class="col-des-6 col-tb-12 col-mb-12 copyright">
                        <address>
                            <?php if($footerBottomCustomCopyright): ?>
                                <?= $customFooterBottomCopyright; ?>
                            <?php else: ?>
                                <?= /* @escapeNotVerified */ $block->getChildHtml('copyright') ?>
                            <?php endif; ?>
                        </address>
                    </div>
                    <div class="col-des-6 col-tb-12 col-mb-12">
                        <!-- Static block: footer_block_menu_bottom -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_menu_bottom')->toHtml() ?>
                    </div>
                </div>
            </div>
		</div>
	<?php elseif($footerVersion == 'footer3'): ?>
        <div class="middle-footer">
            <div class="frame">
                <div class="line">
                    <div class="col-des-3 col-tb-6 col-mb-12">
                        <!-- Static block: footer3_contact_us -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer3_contact_us')->toHtml() ?>
                        <?= $block->getChildHtml('store_switcher'); ?>
                    </div>
                    <div class="col-des-2 col-tb-6 col-mb-12">
                        <!-- Static block: footer_block_categories -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_categories')->toHtml() ?>
                    </div>
                    <div class="col-des-2 col-tb-6 col-mb-12">
                        <!-- Static block: footer_block_infomation -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_infomation')->toHtml() ?>
                    </div>
                    <div class="col-des-2 col-tb-6 col-mb-12">
                        <!-- Static block: footer_block_quick_link -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_quick_link')->toHtml() ?>
                    </div>
                    <div class="col-des-3 col-tb-6 col-mb-12">
                        <!-- Static block: footer_block_subscribe -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_subscribe')->toHtml() ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="bottom-footer">
            <div class="frame">
                <div class="line">
                    <div class="col-des-6 col-tb-12 col-mb-12 copyright">
                        <address>
                            <?php if($footerBottomCustomCopyright): ?>
                                <?= $customFooterBottomCopyright; ?>
                            <?php else: ?>
                                <?= /* @escapeNotVerified */ $block->getChildHtml('copyright') ?>
                            <?php endif; ?>
                        </address>
                    </div>
                    <div class="col-des-6 col-tb-12 col-mb-12">
                        <!-- Static block: footer_block_menu_bottom -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_menu_bottom')->toHtml() ?>
                    </div>
                </div>
            </div>
        </div>
    <?php elseif($footerVersion == 'footer4'): ?>
        <div class="middle-footer">
            <div class="frame">
                <div class="line">
                    <div class="col-des-3 col-tb-6 col-mb-12">
                        <!-- Static block: footer1_logo -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer1_logo')->toHtml() ?>
                    </div>
                    <div class="col-des-3 col-tb-6 col-mb-12">
                        <!-- Static block: footer1_contact_us -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer1_contact_us')->toHtml() ?>
                    </div>
                    <div class="col-des-2 col-tb-6 col-mb-12">
                        <!-- Static block: footer_block_infomation -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_categories')->toHtml() ?>

                    </div>
                    <div class="col-des-2 col-tb-6 col-mb-12">
                        <!-- Static block: footer_block_quick_link -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_infomation')->toHtml() ?>
                    </div>
                    <div class="col-des-2 col-tb-6 col-mb-12">
                        <!-- Static block: footer_block_quick_link -->
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_quick_link')->toHtml() ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="bottom-footer">
            <div class="frame">
                <div class="line">
                    <div class="col-des-12 col-tb-12 col-mb-12 copyright">
                        <address>
                            <?php if($footerBottomCustomCopyright): ?>
                                <?= $customFooterBottomCopyright; ?>
                            <?php else: ?>
                                <?= /* @escapeNotVerified */ $block->getChildHtml('copyright') ?>
                            <?php endif; ?>
                        </address>
                    </div>
                </div>
            </div>
        </div>
	<?php endif ?>
</div>
