<?php
    use Magento\Framework\App\Action\Action;

    $viewMode = 'grid';
    $image = 'category_page_grid';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $_product = $this->getLoadProduct($this->getProductId());
    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
    $productImage = $block->getImage($_product, $image);
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $builderHelper = $this->helper('MGS\Fbuilder\Helper\Data');
    $hideName = $this->getBlockData('hide_name');
    $hideReview = $this->getBlockData('hide_review');
    $getShowReviewsSummary = $this->getShowReviewsSummary() ? true : false;
    $hidePrice = $this->getBlockData('hide_price');
    $hideAddCart = $this->getBlockData('hide_addcart');
    $hideAddWishlist = $this->getBlockData('hide_addwishlist');
    $hideAddCompare = $this->getBlockData('hide_addcompare');
    $themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
    $_imagehelper = $this->helper('MGS\ThemeSettings\Helper\Image');
    $lazyLoad = $themeSettingConfig->getStoreConfig('themesettings/general/lazy_load');
    $baseImage = $this->getViewFileUrl('MGS_ThemeSettings::images/blank.png');
?>
<div class="product-item-info" data-container="product-list">
        <div class="product-image">
            <?php
            $ratio = $this->getRatio() ? $this->getRatio() : null;
            $size = $themeSettingConfig->getImageSize($ratio);
            $padding = $themeSettingConfig->getImagePadding();
            if ($ratio == 1) {
                $padding = '100%';
            }
            ?>

            <?php
            $productImage = $_imagehelper->init($_product, $image)->setImageFile($_product->getData('small_image'))->resize($size['width'], $size['height'])->getUrl();
            $productImageHover = $_imagehelper->init($_product, $image)->setImageFile($_product->getData('thumbnail'))->resize($size['width'], $size['height'])->getUrl();
            ?>
            <?php if(!$lazyLoad): ?>
                <?php $baseImage = $productImage ?>
            <?php endif ?>

            <!-- Product Image-->
            <a href="<?php echo $_product->getProductUrl() ?>"
               class="product photo product-item-photo <?php if ((basename($_product->getData('thumbnail') ?? '') != 'no_selection') && (basename($_product->getData('thumbnail') ?? '') != basename($_product->getData('small_image') ?? ''))): ?> has-hover-image<?php endif ?>"
               style="padding-bottom: <?php echo $padding ?>;" tabindex="-1">

                <img src="<?php echo $baseImage ?>" alt="<?php echo $_productNameStripped ?>"
                     class="img-responsive <?php if ($lazyLoad): ?>arrow-lazy<?php endif ?>"
                     loading="lazy"
                     data-src="<?php echo $productImage ?>"/>
            </a>
            <ul class="actions-link actions-secondary">
                <li>
                    <a data-productid="<?= $_product->getId(); ?>" class="action quickview qv-list" aria-label="Quickview" title="Quickview" href="<?= $this->getUrl().'aquickview/index/index/catalog/product/id/'.$_product->getId(); ?>">
                        <span><?= __('Quickview'); ?></span>
                    </a>
                </li>
                <?php if(($hideAddWishlist!=1)): ?>
                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && ($hideAddWishlist!=1)): ?>
                        <li>
                            <button class="action towishlist"
                                    title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                    data-title="<?php echo __('Add to Wish List') ?>"
                                    aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                    data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                    data-action="add-to-wishlist"
                                    role="button">
                                <i class="pe-7s-like"></i>
                            </button>
                        </li>
                    <?php endif ?>
                <?php endif ?>

                <?php if($hideAddCompare!=1): ?>
                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                    <li>
                        <button class="action tocompare"
                                title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                data-title="<?php echo __('Add to Compare') ?>"
                                aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                role="button">
                            <i class="pe-7s-graph3"></i>
                        </button>
                    </li>
                <?php endif ?>

            </ul>
        </div>

        <?php // Product Detail ?>
        <div class="product details product-item-details">

            <?php if ($hideName!=1): ?>
                <h5 class="product name product-item-name">
                    <a class="product-item-link"
                       href="<?php echo $_product->getProductUrl() ?>">
                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                    </a>
                </h5>
            <?php endif ?>

            <?php if ($hideReview!=1): ?>
                <?php echo $block->getReviewsSummaryHtml($_product, $templateType,$getShowReviewsSummary) ?>
            <?php endif ?>

            <?php if ($hidePrice!=1): ?>
                <?php echo $block->getProductPrice($_product) ?>
            <?php endif ?>

            <?php if (($hideAddCart!=1)): ?>
                <div class="product-item-inner">
                    <div class="product actions product-item-actions">
                        <?php if ($hideAddCart!=1): ?>
                            <div class="actions-primary">
                                <?php if ($_product->isSaleable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form" data-product-sku="<?php echo  /* @NoEscape */ $_product->getSku() ?>" action="<?php echo /* @NoEscape */ $postParams['action'] ?>" method="post">
                                        <input type="hidden" name="product" value="<?php echo /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                        <input type="hidden" name="<?php echo /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?php echo /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                        <?php echo $block->getBlockHtml('formkey') ?>

                                        <?php if($_product->getTypeId() == 'simple'): ?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart btn btn-default btn-xs">
                                                <span><?php echo /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        <?php else: ?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart btn btn-default btn-xs"
                                                    onclick="window.location.href = '<?php echo $block->getProductUrl($_product)?>'">
                                                <span><?php echo /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        <?php endif; ?>
                                    </form>
                                <?php else: ?>
                                    <?php if ($_product->isAvailable()): ?>
                                        <div class="stock available"><span><?php echo /* @escapeNotVerified */ __('In stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?php echo /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        <?php endif ?>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </div>

